version: '3'
services:
  discord-bot:
    build: .
    container_name: discordbot-file-uploader
    environment:
      - TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ${DIRECTORY_PATH}:/app/data
    restart: unless-stopped
